# Generated by Django 4.2.5 on 2023-10-19 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion

def add_preset_order_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('app', 'OrderStatus')
    presets = [
        {"name": "Оформлен", "color": "#36B63E"},
        {"name": "Подтверждён", "color": "#D4EB87"},
        {"name": "Оплачен", "color": "#FFF393"},
        {"name": "Отгржуен", "color": "#1980FF"},
        {"name": "Доставлен", "color": "#C8DEFF"},
        {"name": "Принят", "color": "#87EBF1"},
        {"name": "Завершён", "color": "#535155"},
        {"name": "Отменён", "color": "#FF4E51"},
        {"name": "Возврат", "color": "#FDCDE1"},
    ]
    for preset in presets:
        OrderStatus.objects.create(**preset)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_order_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('color', models.CharField(max_length=10, verbose_name='Фоновый цвет статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderstatus', verbose_name='Статус'),
        ),
        migrations.RunPython(add_preset_order_statuses),
    ]
